Cura 9365 fix building cura main
Ultimaker/cura-binary-data pull request #22
Opened 2022-06-23 07:22 UTC by jellespijker

2022-07-12 11:55 UTC, casperlamboo requested changes

2022-07-12 11:57 UTC, Joeydelarago approved these changes

2022-07-12 12:27 UTC, jellespijker commented on .github/workflows/conan-package.yml
> +            - '[1-9]+.[0-9]+'
Not a regular regex pattern
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

2022-07-13 09:27 UTC, casperlamboo approved these changes

2022-07-13 12:19 UTC, closed without merging